### ISSUE TITLE
import statement does not work as expected

### ISSUE THREAD

**Issue by tomasreichmann** [ZeldaFan0225/ai_horde#13]
I am trying to add this package to a vitejs project which does not support commonjs modules, so I have to use import instead of require. 

I would expect this to work
`import AIHorde, { AIHordeInitOptions } from "@zeldafan0225/ai_horde";`

But it seems all imports are part of the default import instead:
```
console.log("AIHorde", AIHorde);
console.log("AIHorde.AIHorde", AIHorde.AIHorde);
console.log("AIHorde.AIHorde.AIHorde", AIHorde.AIHorde.AIHorde);
```
<img width="480" alt="image" src="https://github.com/ZeldaFan0225/ai_horde/assets/10447001/6553e61d-d12e-463b-99ba-6735f2bbd671">

This causes and error that the named export AIHorde is missing
`import { AIHorde } from "@zeldafan0225/ai_horde";`

**Comment by ZeldaFan0225** [comment]
I will look into it, I don't have a lot of experience with es module only projects.
If it helps maybe take a look at the Discord bot that uses this package.
https://github.com/ZeldaFan0225/ChatGPT-Discord-Bot/blob/main/src/classes/client.ts

**Comment by tomasreichmann** [comment]
Wow, that was quick. GG 👍
