### ISSUE TITLE
postAsyncImageGenerate: How do we add negative prompts?

### ISSUE THREAD

**Issue by abraxas86** [ZeldaFan0225/ai_horde#17]
I can't figure out how/where we would add negative prompts?  I've been going through the docs, but I can't find it.

**Comment by ZeldaFan0225** [comment]
If you have questions about the api itself please refer to the official discord

**Comment by abraxas86** [comment]
I'm not sure... I'm just trying to figure out how to send a packet with my JS code that includes negative prompts to try to get better results back.

This is what I have going right now:

```js
async function sendRequest(job) {
    const allow_downgrade = true;
    const prompt = `${job.prompt}${job.modifier}`;

    try {
        // Convert the '0'/'1' value from the database to a boolean
        const nsfwBoolean = job.nsfw === '1';  // '1' => true, '0' => false

        const response = await ai_horde.postAsyncImageGenerate({
            prompt: prompt,
            nsfw: nsfwBoolean,  // Pass as boolean
            allow_downgrade: allow_downgrade,
            replacement_filter: true,
            token: stableHordeApiKey
        });

        const generationId = response.id;
        await executeUpdate('UPDATE jobs SET generationId = ?, status = 1 WHERE rowid = ?', [generationId, job.rowid]);
        return generationId;
    } catch (err) {
        console.error("[ABX-Conjurebot: conjure-server] Error sending request:", err);
    }
}
```

It works, but the results coming back aren't as good as I think they could be.  I think this would be more in-line with using your NPM package.  If you think it would be better to ask in the Discord server, I'm cool with that too.

**Comment by abraxas86** [comment]
Got the response from the discord.  I honestly wasn't sure if that was the best place, but figured I'd try anyway.

For anybody who happens upon this in the future, after the prompt add `###` and then all your negative prompt terms.
