### ISSUE TITLE
import es6

### ISSUE THREAD

**Issue by scenaristeur** [ZeldaFan0225/ai_horde#9]
Hi , is it possible to use this lib in the browser, with ES6 import ? 
Thxs

**Comment by ZeldaFan0225** [comment]
That's a very good question... I have not tried and am not familiar with what is required to make a package usable in the browser. The package uses NodeJS exclusive features like the file system api so I would assume that it won't work in the browser.

**Comment by scenaristeur** [comment]
As i see readFileSync is only used to read package.json which is not an essential feature ?

**Comment by scenaristeur** [comment]
I've been able to make something  browser side with axios https://scenaristeur.github.io/numerai/

**Comment by ZeldaFan0225** [comment]
I have no idea how to make a browser compatible module. If you want to submit a pull request which implements the required changes to make it compatible feel free to do so, else this is not something on my todo.

**Comment by elix1er** [comment]
so rekt, d.ts shows export {} plz f1x

**Comment by ZeldaFan0225** [comment]
> so rekt, d.ts shows export {} plz f1x

1) open your own issue
2) 1) this repo does not have a index.d.ts file
	2) https://www.npmjs.com/package/@zeldafan0225/ai_horde?activeTab=code Index.d.ts in the package does have exports

**Comment by ZeldaFan0225** [comment]
Browser compatibility was added in #11
